# Generated by Django 3.1.3 on 2022-04-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_auto_20220424_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
